/**
This program can generate Pascal Triangle for as many rows as specified by user.
In addition, it is also possible to limit the number size generated by using modulus operand (%).
The usage:
    ./pascalTriangle arg1 arg2
    where arg1 = no. of rows -- (required),
          arg2 = the modulus value -- if '0' or no input, the default is no modulus, maximum number is UINT_MAX
*/

#include <iostream>
#include <cstdlib>
#include <climits>
#include <vector>
#include <string>

using namespace std;

using Row = vector<int>;

constexpr unsigned DarkBackground = 1;
constexpr unsigned argno = 2;

string rowAsMultiColorString(string leadingSpaces, Row row, unsigned modulo)
{
	string str = leadingSpaces;
	for (auto element : row) {
		str += "\033[1;" + to_string(30 + (element % modulo) % 7 + DarkBackground) + "m"; //the color code prefix
		str += to_string(element % modulo); //the element to print
		str += "\033[0m"; //the suffix to reset the color
		str += " ";
	}
	str.pop_back();
	return str;
}

Row pascalTriangle(int level, unsigned modulo, int leadingSpaces = 0 )
{
	if (level == 0) {
		cout << "invalid argument, aborted" << endl;
		throw;
	} else if (level == 1) {
		Row row = Row{1};
		cout << rowAsMultiColorString(string(leadingSpaces, ' '), row, modulo) << endl;
		return row;
	} else if (level == 2) {
		pascalTriangle(level - 1, modulo, leadingSpaces + 1);
		cout << rowAsMultiColorString(string(leadingSpaces, ' '), Row{1, 1}, modulo) << endl;
		return Row{1, 1};
	} else {
		Row rowAbove = pascalTriangle(level - 1, modulo, leadingSpaces + 1);
		Row row = Row{1};
		for (int i = 1; i < (level - 1); ++i) {
			unsigned int element = rowAbove[i - 1] + rowAbove[i];
			row.push_back(element);
		}
		row.push_back(1);
		cout << rowAsMultiColorString(string(leadingSpaces, ' '), row, modulo) << endl;
		return row;
	}

}

int main(int argc, char* argv[])
{
	if (argc < 2) {
		cout << "Usage: " << argv[0] << " [no. of levels]" << " [optional: modulo]" << endl;
		exit(1);
	}

	int level = atoi(argv[1]);
	unsigned modulo = UINT_MAX;
	if (argc >= 3) modulo = atoi(argv[2]);
	pascalTriangle(level, modulo);
	cout << endl;

	return 0;
}
